plugins {
 	id 'fabric-loom' version "${loom_version}"
}

repositories {
    maven {
        name = "Shedaniel"
        url "https://maven.shedaniel.me/"
    }

    maven { url 'https://jitpack.io' }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}



dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        // parchment("org.parchmentmc.data:parchment-${parchment_mappings_fabric}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    modApi("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    modApi "com.terraformersmc:modmenu:17.0.0-alpha.1"

    implementation("io.github.llamalad7:mixinextras-fabric:${mixinextras_version}")
    annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixinextras_version}")
}

    loom {
        def aw = file("src/main/resources/${mod_id}.accesswidener")
        if (aw.exists()) {
            accessWidenerPath.set(aw)
        }
        mixin {
            defaultRefmapName.set("${mod_id}.refmap.json")
        }
        runs {
            client {
                client()
                setConfigName("Fabric Client")
                ideConfigGenerated(true)
                runDir("run")
            }
            server {
                server()
                setConfigName("Fabric Server")
                ideConfigGenerated(true)
                runDir("run")
            }
        }
    }
task printMinecraftJar { doLast { configurations.compileClasspath.each { println it } } }
